level_1 = [
    "XXXXXXXXXXXXXXXXXXXXXXXXX",
    "XX X  X X        XX   X X",
    "X  X XX XX XXXX XXX X   X",
    "X XX XX XX X XX X XXXX XX",
    "X     X XX    X X  XX   X",
    "XX XX X  X XXXXXXX X  XXX",
    "X   XXXX   T   XX  XX   X",
    "XXX  X XX XXXXXXXX XX XXX",
    "X   XX XX XX  X XX XX X X",
    "XXX XX XX  X XX XX XX X X",
    "X   XX XX XX X T X XX X X",
    "XXX  X  X  X X XXX XX   X",
    "X XX X XX XX X  X  XXXX X",
    "X  X X X  XX XX   XX XX X",
    "X XX X X XXX    X X  X  X",
    "X  T X X     XXXXXXX   XX",
    "XXXX     X X  T  XX  XXXX",
    "XX X XXXXX XX X XXXX XX X",
    "X    X  XXXXXXXXXX X    X",
    "XXXX X XX  X X X X X XX X",
    "X XX X    XX X X P    XXX",
    "X  X X XXXX      XX X T X",
    "XX      T   XXX XXXXXXXXX",
    "X  X X XX X   X         X",
    "XXXXXXXXXXXXXXXDXXXXXXXXX"
]

level_2 = [
    "XXXXXXXXXXXXXXXXXXXXXXXXX",
    "XP     T X X X   XX    XX",
    "XX X X X       XXX  XX  X",
    "XXXXXXXXXXXX X  X  XXXX X",
    "X X   X   XXXXX XX    X X",
    "X XXX XX XX XX     X XXXX",
    "X        XX    X X X    X",
    "XXXXXXXX    X XX X XX XXX",
    "XXXXXX   X XX X  X  X  XX",
    "X    XXX X X  XX X XXX  X",
    "X XX  T  X XX  XXX XX  XX",
    "X  XX X XX XX XXXX  XX  X",
    "XXXXXXXXX  XXXXX   XXX XX",
    "XX X X XXXXX X XXX   X  X",
    "X         T     XX XXXXXX",
    "XX XX XX XXX XX         X",
    "X  XXXX  XXXXXXX X X X XX",
    "X XX XXXXX       X X X XX",
    "X X    XXX XXXXX XXXXX  X",
    "XXXXXX     X   T XX X  XX",
    "X  XXX XXX XXXXX    X XXX",
    "XX     XX  XX    XXXX   X",
    "XXXXXX  XX X  XX   XXXX X",
    "X      XX  XX X  X    X X",
    "XXXXXXXXXXXXXXXXXXXXXXXDX"
           ]


level_3 = ["XXXXXXXXXXXXXXXXXXXXXXXXX",
           "XPXX X           X    X X",
           "X   T  XXXX XX XXX XXXX X",
           "X X XX    XXXXXX X XX X X",
           "X XXXXX X   X XX X      X",
           "X XX  T XXX        X XX X",
           "X X  XX   X X XX XXXXXX X",
           "X X XX  XXXXX XX   T  X X",
           "X X  XX   T XXX  X XXXXXX",
           "X X XXXX XX   XX XXXXX XX",
           "XXXXXX   XX X XX        X",
           "X  X XXX  X X  XX X XXXXX",
           "XX       XX X XX  X   T X",
           "X  X XX XX  X XX XX XX XX",
           "X XX XX  XX XXX  X   X  X",
           "X X  X TXX  XX  XX XXXXXX",
           "XXX XX XXXX  X XXX   XXXX",
           "X    X X  XX X X   X    X",
           "XX X XXXX   TX XXX X XX X",
           "XX X  XX  X XX X   X  XXX",
           "X  XX TX XX  XXXXX XX  XX",
           "X XX  XX XX XXX    TXX  X",
           "X XX XXX  X XX  XX XX  XX",
           "X XX X   XX X  XX   XX  X",
           "XXXXXXXXXXXXXXXXXXXXXXXDX"
           ]
level_4 = ["XXXXXXXXXXXXXXXXXXXXXXXXX",
           "XPXX  X XX X X XX       X",
           "X  XX X X       XXXX XXXX",
           "XX XX X XX XXXXXX    TXXX",
           "X     X X   X X X XX XX X",
           "XXX X   T XXX   X X  X  X",
           "X XXXXXXX XXXX XX XX X XX",
           "X  X X  T X  X XX X T   X",
           "XX   XXXX   XX XX X XXXXX",
           "XXXX X  T XXXX    X X XXX",
           "X    XXXX XX XXX XX  T  X",
           "XXXX X X   X X X  X XXXXX",
           "XX X X XXX    T  XX     X",
           "X        XXX XXXXX  X XXX",
           "XXXXXXX XX X    XX XXXXXX",
           "X X   T  X XX XXX  X X  X",
           "X XXXXXX X X    XX     XX",
           "X  XX XX   X XXXXX XXXXXX",
           "X XXX  XXX X X XX   T   X",
           "X   XX X X X  T   X XXX X",
           "X X    T X X X X XX   X X",
           "X XX XXX   X XXX XXXXXX X",
           "X XXXXXXXX X XX     XXXXX",
           "X X       T   X X X     X",
           "XXXXXDXXXXXXXXXXXXXXXXXXX" ]


blank_maze = [
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         ",
            "                         "
           ]